const ENDPOINT="https://rvkutsfyglopbhrnbotx.supabase.co/functions/v1/workshop-gateway?service=quotes";
const LEGAL_VERSION="UAW-LEGAL-2026-09-10-3";
const TERMS_VERSION="UAW-TERMS-2026-09-10-3";
const PRIVACY_VERSION="UAW-PRIVACY-2026-09-10-3";
const CANCELLATION_VERSION="UAW-CANCEL-2026-09-10-3";
const $=id=>document.getElementById(id);
const token=new URLSearchParams(location.search).get("t")||"";
let quoteData=null,lastApprovalData=null,lastApprovalName="";
const money=n=>`£${Number(n||0).toFixed(2)}`;
const e=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function publicApi(action,payload={}){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload}),cache:"no-store"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Unable to load quote");return data}
function totals(){if(!quoteData)return{parts:0,labour:0,net:0,vat:0,total:0,vatRate:0};const rate=Number(quoteData.quote.labour_rate||0),parts=(quoteData.items||[]).reduce((s,x)=>s+Number(x.quantity||0)*Number(x.unit_price||0),0),labour=(quoteData.items||[]).reduce((s,x)=>s+Number(x.labour_hours||0)*rate,0),net=parts+labour;return{parts,labour,net,vat:0,total:net,vatRate:0,rate}}
function itemSummary(x,rate){const qty=Number(x.quantity||0),unit=Number(x.unit_price||0),hours=Number(x.labour_hours||0),bits=[];if(qty>0||unit>0)bits.push(`${qty} × ${money(unit)} = ${money(qty*unit)}`);if(hours>0)bits.push(`${hours} labour hrs × ${money(rate)} = ${money(hours*rate)}`);return bits.join(" · ")||"No price entered"}
function revisionNotice(quote,versions){if(Number(quote.revision_number||1)<=1)return"";const prev=(versions||[])[0];return `<div class="revision-notice"><b>Revised quote · Revision ${Number(quote.revision_number||1)}</b><p>This replaces the previous estimate for new/additional work. Your earlier approval is retained in the workshop history.</p>${prev?.approved_limit?`<small>Previous authorised limit: ${money(prev.approved_limit)}</small>`:""}</div>`}
function customerMessage(quote){return quote.customer_message?`<div class="customer-quote-message"><span>MESSAGE FROM THE WORKSHOP</span><p>${e(quote.customer_message)}</p></div>`:""}
function rangeSummary(quote,t){const mode=quote.pricing_mode||"fixed",best=Number(quote.best_case_total||t.total),worst=Number(quote.worst_case_total||best);if(mode==="range")return `<div class="approval-range-card"><span>ESTIMATED PRICE RANGE</span><div><b>${money(best)}</b><i>to</i><strong>${money(worst)}</strong></div><p>By approving, you authorise Ultimate Automotive Works LTD to carry out the described work up to a maximum of <b>${money(worst)}</b>. If the repair needs to exceed this amount, we will ask you to approve another revision first.</p></div>`;return `<div class="approval-range-card fixed"><span>FIXED QUOTE</span><div><strong>${money(best)}</strong></div><p>This approval covers the quoted work at the total shown below.</p></div>`}
async function loadQuote(){if(token.length<32){$("approvalTitle").textContent="Invalid approval link";return}try{quoteData=await publicApi("public_quote",{token});const{quote,job,vehicle,customer,items,versions}=quoteData;$("approvalTitle").textContent=`${vehicle?.registration||"Vehicle"} · Job #${job?.job_number||""}`;$("approvalSub").textContent=`${vehicle?.make_model||"Workshop quote"}${customer?.name?` · ${customer.name}`:""}`;const t=totals();$("approvalItems").innerHTML=revisionNotice(quote,versions)+customerMessage(quote)+(items||[]).map((x,index)=>{const lineTotal=(Number(x.quantity||0)*Number(x.unit_price||0))+(Number(x.labour_hours||0)*t.rate);return `<div class="approval-item"><div><small>ITEM ${index+1}</small><b>${e(x.description)}</b><span>${e(itemSummary(x,t.rate))}</span></div><strong>${money(lineTotal)}</strong></div>`}).join("")||"<div class='approval-item'>No quote lines.</div>";$("approvalTotals").innerHTML=rangeSummary(quote,t)+`<h3>${quote.pricing_mode==="range"?"Best-case/current estimate":"Quote total"}</h3><div class="approval-total-grid"><span>Parts</span><b>${money(t.parts)}</b><span>Labour</span><b>${money(t.labour)}</b><span>Subtotal</span><b>${money(t.net)}</b><span>VAT</span><b>Not charged · not VAT registered</b><strong>${quote.pricing_mode==="range"?"Best case":"Total"}</strong><strong>${money(Number(quote.best_case_total||t.total))}</strong>${quote.pricing_mode==="range"?`<strong>Maximum authorised</strong><strong>${money(Number(quote.worst_case_total||quote.best_case_total||t.total))}</strong>`:""}</div>`;const status=String(quote.status||"sent");$("approvalStatus").className=`approval-status ${status}`;$("approvalStatus").textContent=status==="approved"?`Revision ${quote.revision_number||1} approved`:status==="declined"?`Revision ${quote.revision_number||1} declined`:`Revision ${quote.revision_number||1} · Awaiting your decision`;const approveBtn=$("approveQuoteBtn");if(approveBtn)approveBtn.textContent=quote.pricing_mode==="range"?`✓ Approve work up to ${money(Number(quote.worst_case_total||quote.best_case_total||t.total))}`:`✓ Approve quote ${money(Number(quote.best_case_total||t.total))}`;if(status==="sent"||status==="draft"){$("approvalForm").classList.remove("hidden");requestAnimationFrame(()=>requestAnimationFrame(resize))}}catch(err){$("approvalTitle").textContent="Unable to open quote";$("approvalMessage").textContent=err.message;$("approvalMessage").classList.add("error")}}
const canvas=$("customerSig"),ctx=canvas.getContext("2d");let drawing=false,signatureHasInk=false;
function canvasHasInk(){try{if(!canvas.width||!canvas.height)return false;const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;for(let i=3;i<data.length;i+=4)if(data[i]>0)return true}catch(_){}return false}
function resize(){const cssW=Math.max(1,Math.round(canvas.clientWidth||1)),cssH=Math.max(1,Math.round(canvas.clientHeight||1)),w=cssW*2,h=cssH*2;if(canvas.width===w&&canvas.height===h){ctx.setTransform(2,0,0,2,0,0);ctx.lineWidth=2;ctx.lineCap="round";return}const hadInk=signatureHasInk||canvasHasInk();let copy=null;if(hadInk&&canvas.width&&canvas.height){copy=document.createElement("canvas");copy.width=canvas.width;copy.height=canvas.height;copy.getContext("2d").drawImage(canvas,0,0)}canvas.width=w;canvas.height=h;ctx.setTransform(2,0,0,2,0,0);ctx.lineWidth=2;ctx.lineCap="round";if(copy)ctx.drawImage(copy,0,0,copy.width,copy.height,0,0,cssW,cssH);signatureHasInk=hadInk}
function pos(ev){const r=canvas.getBoundingClientRect(),p=ev.touches?ev.touches[0]:ev;return{x:p.clientX-r.left,y:p.clientY-r.top}}
function down(ev){drawing=true;const p=pos(ev);ctx.beginPath();ctx.moveTo(p.x,p.y);ev.preventDefault()}
function move(ev){if(!drawing)return;const p=pos(ev);ctx.lineTo(p.x,p.y);ctx.stroke();signatureHasInk=true;ev.preventDefault()}
function clearCustomerSig(){ctx.clearRect(0,0,canvas.width,canvas.height);signatureHasInk=false}window.clearCustomerSig=clearCustomerSig;
canvas.addEventListener("mousedown",down);canvas.addEventListener("mousemove",move);addEventListener("mouseup",()=>drawing=false);canvas.addEventListener("touchstart",down,{passive:false});canvas.addEventListener("touchmove",move,{passive:false});canvas.addEventListener("touchend",()=>drawing=false);
function renderReceipt(data,name){const receipt=$("approvalReceipt"),details=$("approvalReceiptDetails");if(!receipt||!details||!quoteData)return;const q=quoteData.quote,j=quoteData.job,v=quoteData.vehicle;const when=data.recorded_at?new Date(data.recorded_at).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}):'Recorded by the workshop';details.innerHTML=`<dl class="approval-receipt-grid"><dt>Customer</dt><dd>${e(name)}</dd><dt>Vehicle</dt><dd>${e(v?.registration||'Vehicle')}</dd><dt>Job</dt><dd>#${e(j?.job_number||'')}</dd><dt>Quote revision</dt><dd>${e(data.revision_number||q?.revision_number||1)}</dd><dt>Approved amount</dt><dd>${money(data.approved_total)}</dd><dt>Maximum authorised</dt><dd>${money(data.approved_limit)}</dd><dt>VAT</dt><dd>Not charged · Ultimate Automotive Works LTD is not VAT registered</dd><dt>Recorded</dt><dd>${e(when)}</dd><dt>Early-start requested</dt><dd>${data.early_start_requested?'Yes':'No'}</dd><dt>Terms version</dt><dd>${e(data.terms_version||TERMS_VERSION)}</dd><dt>Privacy version</dt><dd>${e(data.privacy_version||PRIVACY_VERSION)}</dd><dt>Cancellation version</dt><dd>${e(data.cancellation_version||CANCELLATION_VERSION)}</dd></dl>`;receipt.classList.remove("hidden")}
function approvalRecordText(){if(!quoteData||!lastApprovalData)return'';const q=quoteData.quote,j=quoteData.job,v=quoteData.vehicle,d=lastApprovalData,t=totals(),lines=(quoteData.items||[]).map((x,i)=>`${i+1}. ${x.description} — ${itemSummary(x,t.rate)}`).join('\n');return `ULTIMATE AUTOMOTIVE WORKS LTD — CUSTOMER QUOTE APPROVAL RECORD\n\nCompany number: 14995808\nRegistered in England and Wales\nRegistered office: 9 Water Fir Drive, Harworth, Doncaster, England, DN11 8ND\nEmail: ultimateautomotiveworksinquiry@gmail.com\n\nCustomer: ${lastApprovalName}\nVehicle: ${v?.registration||'Vehicle'}${v?.make_model?` · ${v.make_model}`:''}\nJob: #${j?.job_number||''}\nQuote revision: ${d.revision_number||q?.revision_number||1}\n\nWORK AUTHORISED\n${lines||'No item lines recorded'}\n\nApproved amount: ${money(d.approved_total)}\nMaximum authorised: ${money(d.approved_limit)}\nVAT: Not charged — Ultimate Automotive Works LTD is not VAT registered\nRecorded: ${d.recorded_at||''}\nEarly-start requested: ${d.early_start_requested?'Yes':'No'}\n\nLEGAL RECORD\nTerms accepted: Yes\nTerms version: ${d.terms_version||TERMS_VERSION}\nPrivacy information acknowledged: Yes\nPrivacy version: ${d.privacy_version||PRIVACY_VERSION}\nCancellation information acknowledged: Yes\nCancellation version: ${d.cancellation_version||CANCELLATION_VERSION}\nLegal record version: ${d.legal_version||LEGAL_VERSION}\nCustomer signature: Recorded by the workshop system\n\nCurrent legal documents can be viewed at:\nhttps://app.ultimateautomotiveworks.com/terms.html\nhttps://app.ultimateautomotiveworks.com/privacy.html\nhttps://app.ultimateautomotiveworks.com/cancellation.html\n\nKeep this record for your files.`}
function downloadApprovalReceipt(){const text=approvalRecordText();if(!text)return alert('The approval record is available after a quote has been approved.');const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`UAW-approval-job-${quoteData?.job?.job_number||'quote'}-rev-${lastApprovalData?.revision_number||1}.txt`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}window.downloadApprovalReceipt=downloadApprovalReceipt;
async function submitApproval(approved){const name=$("customerApprovalName").value.trim();if(!name){alert("Please enter your name.");return}const termsAck=!!$("approvalTermsAck")?.checked,infoAck=!!$("approvalInfoAck")?.checked,earlyStart=approved&&!!$("approvalEarlyStart")?.checked,signed=signatureHasInk||canvasHasInk();if(approved&&!signed){alert("Please sign inside the signature box before approving the quote.");return}if(approved&&!termsAck){alert("Please read and accept the Workshop Terms before approving.");return}if(approved&&!infoAck){alert("Please read the Privacy Notice and Cancellation Information before approving.");return}let signature="";if(approved){try{signature=canvas.toDataURL("image/png")}catch(_){}}if(!approved&&!confirm("Decline this quote?"))return;try{$("approvalMessage").textContent="Saving your decision…";const data=await publicApi("public_approve",{token,approved,customer_name:name,signature,signature_confirmed:approved?signed:false,terms_accepted:approved?termsAck:false,privacy_acknowledged:approved?infoAck:false,cancellation_info_acknowledged:approved?infoAck:false,early_start_requested:earlyStart,legal_version:LEGAL_VERSION,terms_version:TERMS_VERSION,privacy_version:PRIVACY_VERSION,cancellation_version:CANCELLATION_VERSION,user_agent:navigator.userAgent});$("approvalForm").classList.add("hidden");$("approvalStatus").className=`approval-status ${data.status}`;$("approvalStatus").textContent=data.status==="approved"?`Quote approved${data.approved_limit?` · authorised up to ${money(data.approved_limit)}`:""}`:"Quote declined";$("approvalMessage").textContent=data.status==="approved"?"Your decision, signature and legal acknowledgements have been sent to Ultimate Automotive Works LTD and recorded.":"Your decision has been sent to Ultimate Automotive Works LTD.";if(data.status==="approved"){lastApprovalData=data;lastApprovalName=name;renderReceipt(data,name)}}catch(err){$("approvalMessage").textContent=err.message;$("approvalMessage").classList.add("error")}}window.submitApproval=submitApproval;
resize();addEventListener("resize",()=>requestAnimationFrame(resize));loadQuote();