const ENDPOINT="https://rvkutsfyglopbhrnbotx.supabase.co/functions/v1/workshop-gateway?service=quotes";
const LEGAL_VERSION="UAW-LEGAL-2026-09-10-1";
const $=id=>document.getElementById(id);
const token=new URLSearchParams(location.search).get("t")||"";
let quoteData=null;
const money=n=>`£${Number(n||0).toFixed(2)}`;
const e=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function publicApi(action,payload={}){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Unable to load quote");return data}
function totals(){if(!quoteData)return{parts:0,labour:0,net:0,vat:0,total:0,vatRate:0};const rate=Number(quoteData.quote.labour_rate||0),vatRate=Number(quoteData.quote.vat_rate||0),parts=(quoteData.items||[]).reduce((s,x)=>s+Number(x.quantity||0)*Number(x.unit_price||0),0),labour=(quoteData.items||[]).reduce((s,x)=>s+Number(x.labour_hours||0)*rate,0),net=parts+labour,vat=net*vatRate/100,total=net+vat;return{parts,labour,net,vat,total,vatRate,rate}}
function itemSummary(x,rate){const qty=Number(x.quantity||0),unit=Number(x.unit_price||0),hours=Number(x.labour_hours||0),bits=[];if(qty>0||unit>0)bits.push(`${qty} × ${money(unit)} = ${money(qty*unit)}`);if(hours>0)bits.push(`${hours} labour hrs × ${money(rate)} = ${money(hours*rate)}`);return bits.join(" · ")||"No price entered"}
function revisionNotice(quote,versions){if(Number(quote.revision_number||1)<=1)return"";const prev=(versions||[])[0];return `<div class="revision-notice"><b>Revised quote · Revision ${Number(quote.revision_number||1)}</b><p>This replaces the previous estimate for new/additional work. Your earlier approval is still retained in the workshop history.</p>${prev?.approved_limit?`<small>Previous authorised limit: ${money(prev.approved_limit)}</small>`:""}</div>`}
function customerMessage(quote){return quote.customer_message?`<div class="customer-quote-message"><span>MESSAGE FROM THE WORKSHOP</span><p>${e(quote.customer_message)}</p></div>`:""}
function rangeSummary(quote,t){const mode=quote.pricing_mode||"fixed",best=Number(quote.best_case_total||t.total),worst=Number(quote.worst_case_total||best);if(mode==="range")return `<div class="approval-range-card"><span>ESTIMATED PRICE RANGE</span><div><b>${money(best)}</b><i>to</i><strong>${money(worst)}</strong></div><p>By approving, you authorise Ultimate Automotive Works to carry out the described work up to a maximum of <b>${money(worst)}</b>. If the repair needs to exceed this amount, we will ask you to approve another revision first.</p></div>`;return `<div class="approval-range-card fixed"><span>FIXED QUOTE</span><div><strong>${money(best)}</strong></div><p>This approval covers the quoted work at the total shown below.</p></div>`}
async function loadQuote(){if(token.length<32){$("approvalTitle").textContent="Invalid approval link";return}try{quoteData=await publicApi("public_quote",{token});const{quote,job,vehicle,customer,items,versions}=quoteData;$("approvalTitle").textContent=`${vehicle?.registration||"Vehicle"} · Job #${job?.job_number||""}`;$("approvalSub").textContent=`${vehicle?.make_model||"Workshop quote"}${customer?.name?` · ${customer.name}`:""}`;const t=totals();$("approvalItems").innerHTML=revisionNotice(quote,versions)+customerMessage(quote)+(items||[]).map((x,index)=>{const lineTotal=(Number(x.quantity||0)*Number(x.unit_price||0))+(Number(x.labour_hours||0)*t.rate);return `<div class="approval-item"><div><small>ITEM ${index+1}</small><b>${e(x.description)}</b><span>${e(itemSummary(x,t.rate))}</span></div><strong>${money(lineTotal)}</strong></div>`}).join("")||"<div class='approval-item'>No quote lines.</div>";$("approvalTotals").innerHTML=rangeSummary(quote,t)+`<h3>${quote.pricing_mode==="range"?"Best-case/current estimate":"Quote total"}</h3><div class="approval-total-grid"><span>Parts</span><b>${money(t.parts)}</b><span>Labour</span><b>${money(t.labour)}</b><span>Subtotal</span><b>${money(t.net)}</b><span>VAT (${t.vatRate}%)</span><b>${money(t.vat)}</b><strong>${quote.pricing_mode==="range"?"Best case":"Total"}</strong><strong>${money(Number(quote.best_case_total||t.total))}</strong>${quote.pricing_mode==="range"?`<strong>Maximum authorised</strong><strong>${money(Number(quote.worst_case_total||quote.best_case_total||t.total))}</strong>`:""}</div>`;const status=String(quote.status||"sent");$("approvalStatus").className=`approval-status ${status}`;$("approvalStatus").textContent=status==="approved"?`Revision ${quote.revision_number||1} approved`:status==="declined"?`Revision ${quote.revision_number||1} declined`:`Revision ${quote.revision_number||1} · Awaiting your decision`;const approveBtn=$("approveQuoteBtn");if(approveBtn)approveBtn.textContent=quote.pricing_mode==="range"?`✓ Approve work up to ${money(Number(quote.worst_case_total||quote.best_case_total||t.total))}`:`✓ Approve quote ${money(Number(quote.best_case_total||t.total))}`;if(status==="sent"||status==="draft"){$("approvalForm").classList.remove("hidden");requestAnimationFrame(()=>requestAnimationFrame(resize))}}catch(err){$("approvalTitle").textContent="Unable to open quote";$("approvalMessage").textContent=err.message;$("approvalMessage").classList.add("error")}}
const canvas=$("customerSig"),ctx=canvas.getContext("2d");let drawing=false,signatureHasInk=false;
function canvasHasInk(){try{if(!canvas.width||!canvas.height)return false;const data=ctx.getImageData(0,0,canvas.width,canvas.height).data;for(let i=3;i<data.length;i+=4)if(data[i]>0)return true}catch(_){}return false}
function resize(){const cssW=Math.max(1,Math.round(canvas.clientWidth||1)),cssH=Math.max(1,Math.round(canvas.clientHeight||1)),w=cssW*2,h=cssH*2;if(canvas.width===w&&canvas.height===h){ctx.setTransform(2,0,0,2,0,0);ctx.lineWidth=2;ctx.lineCap="round";return}const hadInk=signatureHasInk||canvasHasInk();let copy=null;if(hadInk&&canvas.width&&canvas.height){copy=document.createElement("canvas");copy.width=canvas.width;copy.height=canvas.height;copy.getContext("2d").drawImage(canvas,0,0)}canvas.width=w;canvas.height=h;ctx.setTransform(2,0,0,2,0,0);ctx.lineWidth=2;ctx.lineCap="round";if(copy)ctx.drawImage(copy,0,0,copy.width,copy.height,0,0,cssW,cssH);signatureHasInk=hadInk}
function pos(ev){const r=canvas.getBoundingClientRect(),p=ev.touches?ev.touches[0]:ev;return{x:p.clientX-r.left,y:p.clientY-r.top}}
function down(ev){drawing=true;const p=pos(ev);ctx.beginPath();ctx.moveTo(p.x,p.y);ev.preventDefault()}
function move(ev){if(!drawing)return;const p=pos(ev);ctx.lineTo(p.x,p.y);ctx.stroke();signatureHasInk=true;ev.preventDefault()}
function clearCustomerSig(){ctx.clearRect(0,0,canvas.width,canvas.height);signatureHasInk=false}window.clearCustomerSig=clearCustomerSig;
canvas.addEventListener("mousedown",down);canvas.addEventListener("mousemove",move);addEventListener("mouseup",()=>drawing=false);canvas.addEventListener("touchstart",down,{passive:false});canvas.addEventListener("touchmove",move,{passive:false});canvas.addEventListener("touchend",()=>drawing=false);
async function submitApproval(approved){const name=$("customerApprovalName").value.trim();if(!name){alert("Please enter your name.");return}const legalAck=!!$("approvalLegalAck")?.checked;const earlyStart=approved&&!!$("approvalEarlyStart")?.checked;const signed=signatureHasInk||canvasHasInk();if(approved&&!signed){alert("Please sign inside the signature box before approving the quote.");return}if(approved&&!legalAck){alert("Please read and accept the Workshop Terms and acknowledge the Privacy Notice and Cancellation Information before approving.");return}let signature="";if(approved){try{signature=canvas.toDataURL("image/png")}catch(_){}}if(!approved&&!confirm("Decline this quote?"))return;try{$("approvalMessage").textContent="Saving your decision…";const data=await publicApi("public_approve",{token,approved,customer_name:name,signature,signature_confirmed:approved?signed:false,terms_accepted:approved?legalAck:false,privacy_acknowledged:approved?legalAck:false,cancellation_info_acknowledged:approved?legalAck:false,early_start_requested:earlyStart,legal_version:LEGAL_VERSION});$("approvalForm").classList.add("hidden");$("approvalStatus").className=`approval-status ${data.status}`;$("approvalStatus").textContent=data.status==="approved"?`Quote approved${data.approved_limit?` · authorised up to ${money(data.approved_limit)}`:""}`:"Quote declined";$("approvalMessage").textContent=data.status==="approved"?"Your decision and legal acknowledgements have been sent to Ultimate Automotive Works and recorded.":"Your decision has been sent to Ultimate Automotive Works."}catch(err){$("approvalMessage").textContent=err.message;$("approvalMessage").classList.add("error")}}window.submitApproval=submitApproval;
resize();addEventListener("resize",()=>requestAnimationFrame(resize));loadQuote();