const ENDPOINT="https://rvkutsfyglopbhrnbotx.supabase.co/functions/v1/workshop-inspections";
const $=id=>document.getElementById(id);
const token=new URLSearchParams(location.search).get("t")||"";
let quoteData=null;
const money=n=>`£${Number(n||0).toFixed(2)}`;
const e=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function publicApi(action,payload={}){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Unable to load quote");return data}
function totals(){if(!quoteData)return{parts:0,labour:0,net:0,vat:0,total:0,vatRate:0};const rate=Number(quoteData.quote.labour_rate||0),vatRate=Number(quoteData.quote.vat_rate||0),parts=(quoteData.items||[]).reduce((s,x)=>s+Number(x.quantity||0)*Number(x.unit_price||0),0),labour=(quoteData.items||[]).reduce((s,x)=>s+Number(x.labour_hours||0)*rate,0),net=parts+labour,vat=net*vatRate/100,total=net+vat;return{parts,labour,net,vat,total,vatRate,rate}}
function itemSummary(x,rate){const qty=Number(x.quantity||0),unit=Number(x.unit_price||0),hours=Number(x.labour_hours||0),bits=[];if(qty>0||unit>0)bits.push(`${qty} × ${money(unit)} = ${money(qty*unit)}`);if(hours>0)bits.push(`${hours} labour hrs × ${money(rate)} = ${money(hours*rate)}`);return bits.join(" · ")||"No price entered"}
async function loadQuote(){if(token.length<32){$("approvalTitle").textContent="Invalid approval link";return}try{quoteData=await publicApi("public_quote",{token});const{quote,job,vehicle,customer,items}=quoteData;$("approvalTitle").textContent=`${vehicle?.registration||"Vehicle"} · Job #${job?.job_number||""}`;$("approvalSub").textContent=`${vehicle?.make_model||"Workshop quote"}${customer?.name?` · ${customer.name}`:""}`;const t=totals();$("approvalItems").innerHTML=(items||[]).map((x,index)=>{const lineTotal=(Number(x.quantity||0)*Number(x.unit_price||0))+(Number(x.labour_hours||0)*t.rate);return `<div class="approval-item"><div><small>ITEM ${index+1}</small><b>${e(x.description)}</b><span>${e(itemSummary(x,t.rate))}</span></div><strong>${money(lineTotal)}</strong></div>`}).join("")||"<div class='approval-item'>No quote lines.</div>";$("approvalTotals").innerHTML=`<h3>Quote total</h3><div class="approval-total-grid"><span>Parts</span><b>${money(t.parts)}</b><span>Labour</span><b>${money(t.labour)}</b><span>Subtotal</span><b>${money(t.net)}</b><span>VAT (${t.vatRate}%)</span><b>${money(t.vat)}</b><strong>Total</strong><strong>${money(t.total)}</strong></div>`;const status=String(quote.status||"sent");$("approvalStatus").className=`approval-status ${status}`;$("approvalStatus").textContent=status==="approved"?"Quote approved":status==="declined"?"Quote declined":"Awaiting your decision";if(status==="sent"||status==="draft")$("approvalForm").classList.remove("hidden")}catch(err){$("approvalTitle").textContent="Unable to open quote";$("approvalMessage").textContent=err.message;$("approvalMessage").classList.add("error")}}
const canvas=$("customerSig"),ctx=canvas.getContext("2d");let drawing=false;
function resize(){canvas.width=canvas.clientWidth*2;canvas.height=canvas.clientHeight*2;ctx.setTransform(2,0,0,2,0,0);ctx.lineWidth=2;ctx.lineCap="round"}
function pos(ev){const r=canvas.getBoundingClientRect(),p=ev.touches?ev.touches[0]:ev;return{x:p.clientX-r.left,y:p.clientY-r.top}}
function down(ev){drawing=true;const p=pos(ev);ctx.beginPath();ctx.moveTo(p.x,p.y);ev.preventDefault()}
function move(ev){if(!drawing)return;const p=pos(ev);ctx.lineTo(p.x,p.y);ctx.stroke();ev.preventDefault()}
function clearCustomerSig(){ctx.clearRect(0,0,canvas.width,canvas.height)}window.clearCustomerSig=clearCustomerSig;
canvas.addEventListener("mousedown",down);canvas.addEventListener("mousemove",move);addEventListener("mouseup",()=>drawing=false);canvas.addEventListener("touchstart",down);canvas.addEventListener("touchmove",move);canvas.addEventListener("touchend",()=>drawing=false);
async function submitApproval(approved){const name=$("customerApprovalName").value.trim();if(!name){alert("Please enter your name.");return}let signature="";try{signature=canvas.toDataURL("image/png")}catch(_){}if(!approved&&!confirm("Decline this quote?"))return;try{$("approvalMessage").textContent="Saving your decision…";const data=await publicApi("public_approve",{token,approved,customer_name:name,signature});$("approvalForm").classList.add("hidden");$("approvalStatus").className=`approval-status ${data.status}`;$("approvalStatus").textContent=data.status==="approved"?"Quote approved — thank you":"Quote declined";$("approvalMessage").textContent="Your decision has been sent to Ultimate Automotive Works."}catch(err){$("approvalMessage").textContent=err.message;$("approvalMessage").classList.add("error")}}window.submitApproval=submitApproval;
resize();addEventListener("resize",resize);loadQuote();