(()=>{
const ENDPOINT='https://rvkutsfyglopbhrnbotx.supabase.co/functions/v1/workshop-gateway?service=monitor',TOKEN_KEY='workshopPinSession';
let installed=false;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function profile(){try{return window.workshopUser||JSON.parse(localStorage.getItem('workshopStaffProfile')||'null')}catch(_){return null}}
async function api(action,payload={}){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','x-workshop-token':localStorage.getItem(TOKEN_KEY)||''},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Monitoring check failed');return d}
function name(t){return({database:'Database',document_storage:'Document storage',custom_domain:'App website'}[t]||t.replaceAll('_',' '))}
function pct(x){return x?.uptime_percent==null?'—':`${Number(x.uptime_percent).toFixed(2)}%`}
function ensureStyle(){if($('monitorV20Style'))return;const s=document.createElement('style');s.id='monitorV20Style';s.textContent=`.monitor-summary-v20{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:12px 0}.monitor-card-v20{background:#101722;border:1px solid #273244;border-radius:16px;padding:15px}.monitor-card-v20.ok{border-bottom:4px solid #22c55e}.monitor-card-v20.warn{border-bottom:4px solid #f59e0b}.monitor-card-v20.down{border-bottom:4px solid #ef4444}.monitor-card-v20 span{display:block;color:#94a3b8;font-size:11px;text-transform:uppercase;letter-spacing:.06em}.monitor-card-v20 b{display:block;font-size:22px;margin:5px 0}.monitor-card-v20 small{color:#94a3b8}.monitor-uptime-v20{display:grid;grid-template-columns:1fr auto auto;gap:8px 14px;align-items:center}.monitor-uptime-v20 span{color:#cbd5e1}.monitor-uptime-v20 b{text-align:right}.monitor-check-row-v20{display:grid;grid-template-columns:1fr auto auto;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid #273244}.monitor-check-row-v20:last-child{border-bottom:0}.monitor-check-row-v20 small{color:#64748b}.monitor-pill-v20{font-size:10px;font-weight:900;padding:5px 8px;border-radius:999px;text-transform:uppercase}.monitor-pill-v20.ok{background:#123b25;color:#86efac}.monitor-pill-v20.warn{background:#452f0b;color:#fcd34d}.monitor-pill-v20.down{background:#47161a;color:#fca5a5}@media(max-width:560px){.monitor-summary-v20{grid-template-columns:1fr}.monitor-check-row-v20{grid-template-columns:1fr auto}.monitor-check-row-v20>small:last-child{grid-column:1/-1}}`;document.head.appendChild(s)}
async function render(){ensureStyle();const view=$('opsView');if(!view)return;if(profile()?.role!=='admin'){view.innerHTML='<div class="ops-empty">Admin access is required for monitoring.</div>';return}view.innerHTML='<div class="ops-loading">Loading automated monitoring…</div>';try{const d=await api('dashboard'),latest={};for(const x of d.recent||[])if(!latest[x.target])latest[x.target]=x;view.innerHTML=`<div class="screen-title"><p class="eyebrow">RELIABILITY</p><h1>Automated Monitoring</h1><p class="muted">The workshop website, database and document storage are checked automatically every 15 minutes.</p></div><div class="monitor-summary-v20">${['custom_domain','database','document_storage'].map(t=>{const x=latest[t],s=x?.status||'warn';return`<div class="monitor-card-v20 ${s}"><span>${name(t)}</span><b>${s==='ok'?'✓ Online':s==='down'?'× Down':'! Check'}</b><small>${x?`${x.latency_ms||0} ms · ${new Date(x.checked_at).toLocaleTimeString('en-GB')}`:'Waiting for first check'}</small></div>`}).join('')}</div><div class="ops-card"><div class="section-heading"><div><p class="eyebrow">UPTIME</p><h2>Availability history</h2></div><button class="primary" onclick="runWorkshopMonitorNow(this)">Check now</button></div><div class="monitor-uptime-v20"><span>Component</span><b>24 hours</b><b>7 days</b>${['custom_domain','database','document_storage'].map(t=>`<span>${name(t)}</span><b>${pct(d.uptime_24h?.[t])}</b><b>${pct(d.uptime_7d?.[t])}</b>`).join('')}</div></div><div class="ops-card"><h2>Recent checks</h2>${(d.recent||[]).slice(0,18).map(x=>`<div class="monitor-check-row-v20"><div><b>${name(x.target)}</b><small>${new Date(x.checked_at).toLocaleString('en-GB')}</small></div><span class="monitor-pill-v20 ${x.status}">${x.status}</span><small>${x.latency_ms||0} ms${x.http_status?` · HTTP ${x.http_status}`:''}</small></div>`).join('')||'<p class="ops-note">No checks recorded yet.</p>'}</div><div class="ops-card"><p class="eyebrow">AUTOMATIC</p><h2>What is being watched</h2><p class="ops-note">Every 15 minutes the monitor checks that your custom app domain responds correctly, the Supabase workshop database can be reached, and the private document storage is available. Failures are recorded here even when nobody has the app open.</p></div>`}catch(e){view.innerHTML=`<div class="ops-card"><h2>Monitoring unavailable</h2><p class="profit-negative">${esc(e.message)}</p><button class="primary" onclick="runWorkshopMonitorNow(this)">Try again</button></div>`}}
window.runWorkshopMonitorNow=async button=>{const b=button||null;if(b){b.disabled=true;b.textContent='Checking…'}try{await api('run_now');await render()}catch(e){alert(e.message)}finally{if(b){b.disabled=false;b.textContent='Check now'}}};
function install(){if(installed||!window.showTool||!$('opsNav'))return;installed=true;const old=window.showTool;window.showTool=function(tool){if(tool==='monitor'){document.querySelectorAll('#opsNav button').forEach(b=>b.classList.toggle('active',b.dataset.tool==='monitor'));const u=new URL(location.href);u.searchParams.set('tool','monitor');history.replaceState(null,'',u);render();return}return old.apply(this,arguments)};if(profile()?.role==='admin'&&!$('opsNav').querySelector('[data-tool="monitor"]')){const b=document.createElement('button');b.dataset.tool='monitor';b.onclick=()=>window.showTool('monitor');b.innerHTML='<span>📡</span><b>Monitoring</b>';$('opsNav').appendChild(b)}if(new URLSearchParams(location.search).get('tool')==='monitor')setTimeout(()=>window.showTool('monitor'),350)}
function mainTile(){const launch=document.querySelector('#home .workshop-launch');if(!launch||profile()?.role!=='admin'||$('monitorHomeTileV20'))return;const b=document.createElement('button');b.id='monitorHomeTileV20';b.className='workshop-tile';b.innerHTML='<span>📡</span><b>Automated Monitoring</b><small>Website, database & storage uptime</small>';b.onclick=()=>location.href='operations.html?tool=monitor&v=20';launch.appendChild(b)}
let tries=0;const timer=setInterval(()=>{tries++;install();mainTile();if(tries>500)clearInterval(timer)},200);document.addEventListener('DOMContentLoaded',()=>{install();mainTile()});
})();