(()=>{
const QUEUE_KEY='workshopOfflineQueueV20',MAIN_CACHE='workshopOfflineCacheMainV20',TOKEN_KEY='workshopPinSession';
const SYNC='https://rvkutsfyglopbhrnbotx.supabase.co/functions/v1/workshop-gateway?service=sync';
let syncing=false,lastError='';
const $=id=>document.getElementById(id);
const uid=()=>{try{return crypto.randomUUID()}catch(_){return`op-${Date.now()}-${Math.random().toString(36).slice(2)}`}};
const getQueue=()=>{try{const q=JSON.parse(localStorage.getItem(QUEUE_KEY)||'[]');return Array.isArray(q)?q:[]}catch(_){return[]}};
const putQueue=q=>{localStorage.setItem(QUEUE_KEY,JSON.stringify(q));renderStatus();document.dispatchEvent(new CustomEvent('workshop-offline-queue',{detail:{count:q.length}}))};
function cachedMain(){try{return JSON.parse(localStorage.getItem(MAIN_CACHE)||'null')}catch(_){return null}}
function regKey(v){return String(v||'').replace(/\s+/g,'').toUpperCase()}
function queued(type,payload,label,dedupeKey=''){
 let q=getQueue(),op={id:uid(),type,payload,label:label||type,created_at:new Date().toISOString(),dedupe_key:dedupeKey||null};
 if(dedupeKey){const i=q.findIndex(x=>x.dedupe_key===dedupeKey);if(i>=0){op.id=q[i].id;op.created_at=q[i].created_at;q[i]=op}else q.push(op)}else q.push(op);
 putQueue(q);return op;
}
function addStyle(){if($('offlineV20Style'))return;const s=document.createElement('style');s.id='offlineV20Style';s.textContent=`.offline-status-v20{position:fixed;z-index:9998;right:max(12px,env(safe-area-inset-right));bottom:max(12px,env(safe-area-inset-bottom));display:flex;align-items:center;gap:8px;max-width:calc(100vw - 24px);padding:9px 12px;border:1px solid #334155;border-radius:999px;background:#0b1220eF;color:#e2e8f0;box-shadow:0 10px 30px #0008;font:700 12px/1.2 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;backdrop-filter:blur(12px)}.offline-status-v20 b{width:8px;height:8px;border-radius:50%;background:#22c55e;flex:none}.offline-status-v20.offline b{background:#f59e0b}.offline-status-v20.queued b{background:#ef4444}.offline-status-v20.syncing b{background:#38bdf8;animation:offlinePulse .8s infinite alternate}.offline-status-v20 button{border:0;background:none;color:#f87171;font:inherit;padding:0;cursor:pointer}.offline-status-v20 small{color:#94a3b8;font-weight:600}@keyframes offlinePulse{to{opacity:.35}}@media(max-width:520px){.offline-status-v20{left:12px;right:12px;justify-content:center;border-radius:14px}}@media print{.offline-status-v20{display:none!important}}`;document.head.appendChild(s)}
function renderStatus(){addStyle();let x=$('offlineStatusV20');if(!x){x=document.createElement('div');x.id='offlineStatusV20';x.className='offline-status-v20';document.body.appendChild(x)}const count=getQueue().length,online=navigator.onLine!==false;x.className='offline-status-v20 '+(syncing?'syncing':!online?'offline':count?'queued':'');if(syncing)x.innerHTML='<b></b><span>Syncing workshop changes…</span>';else if(!online)x.innerHTML=`<b></b><span>Offline mode</span>${count?`<small>${count} change${count===1?'':'s'} waiting</small>`:'<small>work is saved on this device</small>'}`;else if(count)x.innerHTML=`<b></b><span>${count} change${count===1?'':'s'} waiting to sync</span><button type="button" id="offlineSyncNow">Sync now</button>`;else x.innerHTML='<b></b><span>Online · synced</span>';setTimeout(()=>{$('offlineSyncNow')?.addEventListener('click',syncNow,{once:true})},0)}
async function syncNow(){if(syncing||navigator.onLine===false)return false;let q=getQueue();if(!q.length){try{await window.refreshSharedInspections?.()}catch(_){}renderStatus();return true}const token=localStorage.getItem(TOKEN_KEY)||'';if(!token){lastError='Sign in before syncing';renderStatus();return false}syncing=true;lastError='';renderStatus();try{const r=await fetch(SYNC,{method:'POST',headers:{'Content-Type':'application/json','x-workshop-token':token},body:JSON.stringify({action:'sync_batch',operations:q})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Sync failed (${r.status})`);const ok=new Set((d.results||[]).filter(x=>x.ok).map(x=>x.id));const failed=(d.results||[]).filter(x=>!x.ok);q=q.filter(x=>!ok.has(x.id));putQueue(q);if(failed.length)lastError=failed[0].error||'Some changes could not sync';try{await window.refreshSharedInspections?.()}catch(_){}try{await window.workshopRefresh?.()}catch(_){}document.dispatchEvent(new CustomEvent('workshop-sync-complete',{detail:{remaining:q.length,failed}}));return !q.length}catch(e){lastError=e.message||'Sync failed';console.warn('Workshop auto sync failed',e);return false}finally{syncing=false;renderStatus()}}
function jobSnapshot(){const title=$('jobTitle')?.textContent||'',m=title.match(/Job\s*#(\d+)/i),jobNumber=m?Number(m[1]):0,vehicleId=$('jobVehicle')?.value||'',cache=cachedMain(),existing=jobNumber?(cache?.jobs||[]).find(j=>Number(j.job_number)===jobNumber):null;return{job_number:jobNumber,job:{id:existing?.id||null,vehicle_id:vehicleId,customer_id:existing?.customer_id||null,inspection_client_id:$('jobForm')?.dataset.inspectionId||existing?.inspection_client_id||null,status:$('jobStatus')?.value||'Booked In',technician:$('jobTechnician')?.value||'',booked_for:$('jobBookedFor')?.value?new Date($('jobBookedFor').value).toISOString():null,work_summary:$('jobWorkSummary')?.value||'',customer_notes:$('jobCustomerNotes')?.value||'',private_notes:$('jobPrivateNotes')?.value||'',progress_percent:Number($('jobProgressRange')?.value||existing?.progress_percent||10),estimated_ready_at:$('jobEstimatedReady')?.value?new Date($('jobEstimatedReady').value).toISOString():null,customer_progress_note:$('jobProgressNote')?.value||''}}}
function vehicleSnapshot(){const reg=($('vfReg')?.value||'').trim().toUpperCase(),cache=cachedMain(),existing=(cache?.vehicles||[]).find(v=>regKey(v.registration)===regKey(reg)),customer=existing?(cache?.customers||[]).find(c=>c.id===existing.customer_id):null;return{customer:{id:customer?.id||null,name:$('vfCustomerName')?.value||'',phone:$('vfPhone')?.value||'',email:$('vfEmail')?.value||'',notes:$('vfCustomerNotes')?.value||''},vehicle:{id:existing?.id||null,registration:reg,make_model:$('vfModel')?.value||'',year:$('vfYear')?.value||'',mileage:$('vfMileage')?.value||'',vin:$('vfVin')?.value||'',mot_due:$('vfMotDue')?.value||'',service_due_date:$('vfServiceDue')?.value||'',service_due_mileage:$('vfServiceMileage')?.value||'',notes:$('vfVehicleNotes')?.value||''}}}
function quoteSnapshot(){const m=($('quoteTitle')?.textContent||'').match(/Job\s*#(\d+)/i),jobNumber=m?Number(m[1]):0,rate=Number($('labourRate')?.value||0),vat=Number($('vatRate')?.value||0),items=[...document.querySelectorAll('#quoteLines .quote-line')].map(line=>{const i=line.querySelectorAll('input');return{description:i[0]?.value||'',quantity:Number(i[1]?.value||0),unit_price:Number(i[2]?.value||0),labour_hours:Number(i[3]?.value||0),approved:true,item_type:Number(i[3]?.value||0)>0&&Number(i[1]?.value||0)===0?'labour':'part'}}),net=items.reduce((s,x)=>s+x.quantity*x.unit_price+x.labour_hours*rate,0),best=Math.round(net*(1+vat/100)*100)/100,mode=$('quotePricingMode')?.value==='range'?'range':'fixed',worst=mode==='range'?Number($('quoteWorstCase')?.value||best):best;return{job_number:jobNumber,quote:{labour_rate:rate,vat_rate:vat,pricing_mode:mode,worst_case_total:worst,customer_message:$('quoteCustomerMessage')?.value||''},items,best}}
function installWrappers(){
 if(window.saveVehicle&&!window.saveVehicle.__offlineV20){const old=window.saveVehicle;const w=async(...a)=>{if(navigator.onLine!==false)return old.apply(this,a);const p=vehicleSnapshot();if(!p.vehicle.registration){alert('Please enter the vehicle registration.');return}queued('vehicle_save',p,`Vehicle ${p.vehicle.registration}`,`vehicle:${regKey(p.vehicle.registration)}`);alert('Customer and vehicle saved offline. It will sync automatically when the connection returns.')};w.__offlineV20=true;window.saveVehicle=w}
 if(window.saveJob?.__progressV16&&!window.saveJob.__offlineV20){const old=window.saveJob;const w=async(...a)=>{if(navigator.onLine!==false)return old.apply(this,a);const p=jobSnapshot();if(!p.job.vehicle_id){alert('Please choose a vehicle first.');return}queued('job_save',p,p.job_number?`Job #${p.job_number}`:'New job',p.job_number?`job:${p.job_number}`:'');alert('Job card and customer progress saved offline. They will sync automatically when the connection returns.')};w.__offlineV20=true;w.__progressV16=true;window.saveJob=w}
 if(window.saveQuote?.__quoteRevisionV18&&!window.saveQuote.__offlineV20){const old=window.saveQuote;const w=async(...a)=>{if(navigator.onLine!==false)return old.apply(this,a);const p=quoteSnapshot();if(!p.job_number){alert('Save and sync the job card before creating its quote offline.');return null}if(!p.items.length){alert('Add at least one quote item.');return null}if(p.quote.pricing_mode==='range'&&p.quote.worst_case_total<p.best){alert(`Worst-case maximum must be at least £${p.best.toFixed(2)}.`);return null}queued('quote_save',p,`Quote for Job #${p.job_number}`,`quote:${p.job_number}`);alert('Quote saved offline. It will sync automatically. Customer approval links require a connection.');return{offline_queued:true}};w.__offlineV20=true;w.__quoteRevisionV18=true;window.saveQuote=w}
 if(window.createApprovalLink&&!window.createApprovalLink.__offlineV20){const old=window.createApprovalLink;const w=async(...a)=>{if(navigator.onLine===false){await window.saveQuote?.();alert('The quote is stored offline. Reconnect before creating the secure customer approval link.');return}return old.apply(this,a)};w.__offlineV20=true;window.createApprovalLink=w}
 if(window.saveCustomerProgress&&!window.saveCustomerProgress.__offlineV20){const old=window.saveCustomerProgress;const w=async(...a)=>{if(navigator.onLine!==false)return old.apply(this,a);const jobId=$('pgJob')?.value||'';if(!jobId)return;const p={job_id:jobId,progress_percent:Number($('pgProgress')?.value||0),estimated_ready_at:$('pgReady')?.value?new Date($('pgReady').value).toISOString():null,customer_progress_note:$('pgNote')?.value||''};queued('progress_save',p,'Customer progress',`progress:${jobId}`);const state=$('pgState');if(state)state.textContent='✓ Saved offline — will update the customer portal automatically when online.'};w.__offlineV20=true;window.saveCustomerProgress=w}
}
window.WorkshopOffline={queue:queued,sync:syncNow,count:()=>getQueue().length,isOffline:()=>navigator.onLine===false};
window.addEventListener('online',()=>{renderStatus();setTimeout(syncNow,500)});window.addEventListener('offline',renderStatus);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&navigator.onLine!==false)syncNow()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw-v20.js?v=20',{scope:'./'}).catch(e=>console.warn('Offline cache unavailable',e)));
let tries=0;const timer=setInterval(()=>{tries++;installWrappers();if(tries>600)clearInterval(timer)},200);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{renderStatus();installWrappers();setTimeout(syncNow,1200)});else{renderStatus();installWrappers();setTimeout(syncNow,1200)}
setInterval(()=>{if(navigator.onLine!==false&&getQueue().length)syncNow()},60000);
})();