(()=>{
const ENDPOINT="https://rvkutsfyglopbhrnbotx.supabase.co/functions/v1/workshop-gateway?service=customer";
const TOKEN_KEY="workshopPinSession";
const $=id=>document.getElementById(id);
let manualProgress=false,loadSeq=0;
const statusDefault=s=>({"Booked In":10,"Awaiting Approval":20,"Awaiting Parts":35,"In Progress":60,"Completed":100,"Collected":100,"Cancelled":0}[s]??25);
const localDT=v=>{if(!v)return"";const d=new Date(v),p=n=>String(n).padStart(2,"0");return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
function etaText(v){if(!v)return"No estimated ready time set";const d=new Date(v),diff=d-Date.now();if(!Number.isFinite(diff))return"";if(diff<=0)return"Estimated ready time has passed";const mins=Math.ceil(diff/60000),days=Math.floor(mins/1440),hrs=Math.floor((mins%1440)/60),m=mins%60;return days?`Approx. ${days}d ${hrs}h remaining`:hrs?`Approx. ${hrs}h ${m}m remaining`:`Approx. ${m} min remaining`}
async function api(action,payload={}){const r=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","x-workshop-token":localStorage.getItem(TOKEN_KEY)||""},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Progress request failed (${r.status})`);return d}
function injectStyle(){if($("progressV16Style"))return;const s=document.createElement("style");s.id="progressV16Style";s.textContent=`.customer-progress-editor{margin-top:8px;padding:15px;border:1px solid #273244;border-radius:16px;background:#101722}.customer-progress-editor h2{margin:0 0 4px}.customer-progress-editor .progress-copy{color:#94a3b8;font-size:12px;margin:0 0 14px}.job-progress-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px}.job-progress-head b{font-size:20px;color:#fca5a5}.job-progress-range{width:100%;accent-color:#ef2b2d}.job-progress-track{height:9px;background:#202a37;border-radius:999px;overflow:hidden;margin:8px 0 14px}.job-progress-track span{display:block;height:100%;background:linear-gradient(90deg,#b81419,#ef2b2d);border-radius:999px;transition:width .2s}.job-progress-grid{display:grid;grid-template-columns:1fr;gap:10px}.job-progress-editor-note{font-size:11px;color:#94a3b8;margin:8px 0 0}.lead-preview{display:block;color:#fca5a5;font-size:12px;font-weight:800;margin-top:6px}`;document.head.appendChild(s)}
function ensureEditor(){const form=$("jobForm")?.querySelector(".form");if(!form||$("customerProgressEditor"))return !!$("customerProgressEditor");injectStyle();const box=document.createElement("section");box.id="customerProgressEditor";box.className="customer-progress-editor";box.innerHTML=`<h2>Customer progress & lead time</h2><p class="progress-copy">Shown live in the customer's secure vehicle portal.</p><div class="job-progress-head"><span>Job progress</span><b id="jobProgressValue">10%</b></div><input id="jobProgressRange" class="job-progress-range" type="range" min="0" max="100" step="5" value="10"><div class="job-progress-track"><span id="jobProgressBar" style="width:10%"></span></div><div class="job-progress-grid"><label>Estimated ready / lead time<input id="jobEstimatedReady" type="datetime-local"><small id="jobLeadPreview" class="lead-preview">No estimated ready time set</small></label><label>Customer progress update<textarea id="jobProgressNote" placeholder="e.g. Service completed. Waiting for front brake pads to arrive."></textarea></label></div><p class="job-progress-editor-note">Use the percentage for the progress bar. The estimated ready time gives the customer a live lead-time estimate.</p>`;const booked=$("jobBookedFor")?.parentElement;booked?.insertAdjacentElement("afterend",box)||form.appendChild(box);$("jobProgressRange")?.addEventListener("input",()=>{manualProgress=true;renderProgress()});$("jobEstimatedReady")?.addEventListener("input",renderLead);$("jobStatus")?.addEventListener("change",()=>{if(!manualProgress)setProgress(statusDefault($("jobStatus").value),false)});return true}
function renderProgress(){const val=Math.max(0,Math.min(100,Number($("jobProgressRange")?.value||0)));if($("jobProgressValue"))$("jobProgressValue").textContent=`${val}%`;if($("jobProgressBar"))$("jobProgressBar").style.width=`${val}%`}
function renderLead(){if($("jobLeadPreview"))$("jobLeadPreview").textContent=etaText($("jobEstimatedReady")?.value)}
function setProgress(v,manual=false){ensureEditor();if($("jobProgressRange"))$("jobProgressRange").value=String(Math.max(0,Math.min(100,Number(v)||0)));manualProgress=manual;renderProgress()}
function clearProgress(){ensureEditor();setProgress(statusDefault($("jobStatus")?.value||"Booked In"),false);if($("jobEstimatedReady"))$("jobEstimatedReady").value="";if($("jobProgressNote"))$("jobProgressNote").value="";renderLead()}
async function loadProgress(jobId){const seq=++loadSeq;ensureEditor();try{const r=await api("progress_get",{job_id:jobId});if(seq!==loadSeq)return;setProgress(r.job.progress_percent??statusDefault(r.job.status),false);if($("jobEstimatedReady"))$("jobEstimatedReady").value=localDT(r.job.estimated_ready_at);if($("jobProgressNote"))$("jobProgressNote").value=r.job.customer_progress_note||"";renderLead()}catch(e){console.warn("Progress load failed",e)}}
async function saveProgressByNumber(jobNumber,snapshot){if(!jobNumber)return;await api("progress_save",{job_number:jobNumber,progress_percent:snapshot.progress,estimated_ready_at:snapshot.ready?new Date(snapshot.ready).toISOString():null,customer_progress_note:snapshot.note})}
function snapshot(){return{progress:Number($("jobProgressRange")?.value||0),ready:$("jobEstimatedReady")?.value||"",note:$("jobProgressNote")?.value||""}}
function install(){if(!window.newJob||!window.openJob||!window.saveJob||!$("jobForm"))return false;if(window.saveJob.__progressV16)return true;ensureEditor();const oldNew=window.newJob,oldOpen=window.openJob,oldSave=window.saveJob;
window.newJob=function(...a){const r=oldNew.apply(this,a);clearProgress();return r};
window.openJob=function(id,...a){const r=oldOpen.call(this,id,...a);manualProgress=false;loadProgress(id);return r};
const wrapped=async function(...a){ensureEditor();const snap=snapshot();await oldSave.apply(this,a);const m=($("jobTitle")?.textContent||"").match(/Job\s*#(\d+)/i);if(!m)return;try{await saveProgressByNumber(Number(m[1]),snap);setProgress(snap.progress,false);if($("jobEstimatedReady"))$("jobEstimatedReady").value=snap.ready;if($("jobProgressNote"))$("jobProgressNote").value=snap.note;renderLead()}catch(e){alert(`Job card saved, but customer progress could not be saved: ${e.message}`)}};wrapped.__progressV16=true;window.saveJob=wrapped;return true}
let tries=0;const timer=setInterval(()=>{tries++;if(install()||tries>80)clearInterval(timer)},100);document.addEventListener("DOMContentLoaded",()=>{ensureEditor();install()});
})();